name: adopt_petz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  adaptive_theme: ^3.2.1
  day_night_switch: ^1.0.3
  cached_network_image: ^3.2.3
  easy_image_viewer: ^1.2.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
